### PR TITLE
Step5 set up k8s

### PR DESCRIPTION
**Pull request by zimmermantr**
Created all of the files I needed to get this thing running on minikube. Changes will need to be made for EKS, but hopefully not a lot.

TAKE NOTE: kubectl create configmap db-backup-configmap --from-file=db_backup.sql -n shredder
That command needs to be ran in order to get the data loaded in. I created a script that you can manually follow or just run it. 

Some of the weird additions that you might not recognize were to get this data loaded on startup.

### CODE REVIEW

**Review by its-michaelroy — COMMENTED** [review]
Looks good. Requesting another reviewer before approval.

**Review by CassandraGross1 — CHANGES_REQUESTED** [review]
@zimmermantr Do you intend to have the secrets.yml uploaded?   I am sending this back with everything else approved except for the secrets.yml.  Once you respond, I will review again and approve.

**Review by its-michaelroy — APPROVED** [review]

**Review by its-michaelroy — APPROVED** [review]

**Review by its-michaelroy — APPROVED** [review]

**Review by its-michaelroy — APPROVED** [review]
Updated to remove secrets

**Review by CassandraGross1 — APPROVED** [review]
Approving since secrets file removed.

**Pull request merged**
